### ISSUE TITLE
Add docs

### ISSUE THREAD

**Issue by LovelyBuggies** [scikit-hep/mplhep#102]
As @HDembinski mentioned in issue #96, more generally, we should add docs. Buiding docs using Sphinx and RTD like boost-histogram is a good option.

**Comment by andrzejnovak** [comment]
I am currently out for vacation, so I don't think I'll get to it soon, but a PR on this would be welcome.

**Comment by andrzejnovak** [comment]
Nominal docs added. I'm going to see if I can improve a few things. https://mplhep.readthedocs.io/en/latest/

It seems coffea has part of the docs built automatically out of example notebooks which would be an ideal solution for use, also solving #96 and #97.
