### ISSUE TITLE
Conda installation

### ISSUE THREAD

**Issue by LovelyBuggies** [scikit-hep/mplhep#107]
Could we install it only by `pip`? Is there a conda channel?

**Comment by andrzejnovak** [comment]
I didn't think it was necessary, but I don't have anything against it. I have not done it, due to time constraints.

**Comment by LovelyBuggies** [comment]
I think it would be helpful to have a conda installation if you have time in the future.

**Comment by eduardo-rodrigues** [comment]
Pinging @chrisburr in case he has not seen this thread. He's been putting much of Scikit-HEP on conda.

**Comment by andrzejnovak** [comment]
@LovelyBuggies Seems we got it working. 
https://github.com/conda-forge/mplhep-feedstock

Gonna close this now.

**Comment by LovelyBuggies** [comment]
Okay, it's good.
