### ISSUE TITLE
Use snake_case instead of joinedwords

### ISSUE THREAD

**Issue by HDembinski** [scikit-hep/mplhep#123]
- [ ] lhcb.py: lhcbtext, lhcblabel should these even be public?
- [ ] cms.py: cmstext, cmslabel, same?
- [ ] atlas.py: atlastext, atlaslabel, same?

**Comment by andrzejnovak** [comment]
👍 for snake case
I think public is ok, for both.
- `<exp>label` - is predefined and only takes bools and lumi number to set it for the defaults of being preliminary or not or simulation or not (I can see this being heavy-handed, but it covers 90% of plot labels)
- `<exp>text` is for the edge cases when you want some custom label like `CMS Work-in-progress` or `CMS Private Work`
