### ISSUE TITLE
Support for matplotlib 3.1?

### ISSUE THREAD

**Issue by nsmith-** [scikit-hep/mplhep#127]
Is FontManager critical? i.e. could we detect mpl version on import and do the appropriate so we can still use mplhep with (slightly) older mpl

**Comment by andrzejnovak** [comment]
Hmm, since this is the second time it comes up, I'll add it back, but what is the issue with having mpl 3.2?

**Comment by nsmith-** [comment]
It's just what is on LCG96. Of course that isn't the greatest reason, but it is popular for those who want to use condor jobs for their work (lightens the virtualenv usercode a lot)
