### ISSUE TITLE
Stacking a single histogram

### ISSUE THREAD

**Issue by AndreasAlbert** [scikit-hep/mplhep#129]
Hi,

I am wondering about the explicit check of the number of histograms in a stack [here](https://github.com/scikit-hep/mplhep/blob/master/mplhep/plot.py#L140-L141). 

I run into this check a lot when I e.g. select datasets in my coffea histograms to be overlaid using a regular expression. In order to produce many plots in an automated way, I'd  like to be able to use the same plotting code whether my regex matches 1 or N>1 data sets.

I tried simply removing the check and the code runs fine, which is also what  I'd have expected since a single-histogram stack is well-defined. Are there any strong reasons to abort plotting in this case?

**Comment by andrzejnovak** [comment]
Imho it was put in due to earlier implementation of stacking.  Can you submit a PR?

**Comment by andrzejnovak** [comment]
:+1:
