### ISSUE TITLE
cmslabel() doesn't work as documented

### ISSUE THREAD

**Issue by lmoureaux** [scikit-hep/mplhep#151]
The `README` gives the following example:
```py
ax = hep.cms.cmslabel(ax, data=False, paper=False, year='2017')
```

However this syntax fails:
```
Traceback (most recent call last):
  File "plot-migration-maps.py", line 52, in <module>
    ax = hep.cms.cmslabel(ax, data=False, paper=False, year='2017')
TypeError: cmslabel() takes 0 positional arguments but 1 was given
```

One needs to pass `ax=ax` as the first argument. The original syntax was working in January, I'm not sure if the change was intended, but either the `README` should be updated or the argument list fixed ;)

btw thank you for this great library!

**Comment by andrzejnovak** [comment]
@lmoureaux Thanks for letting me know. I need to update the readme. The change was made because I think in most cases the correct axis is implied (the most recent one) but if it needs to be specified it can always be passed as kwarg. So users can usually just write
```
hep.cms.cmslabel()
```
as opposed to 
```
hep.cms.cmslabel(ax)
```

**Comment by andrzejnovak** [comment]
Fixed.
