### ISSUE TITLE
Use 'ndim' instead of 'rank'

### ISSUE THREAD

**Issue by jpivarski** [scikit-hep/mplhep#159]
![image](https://user-images.githubusercontent.com/1852447/87230119-13427800-c373-11ea-9e47-52258a186953.png)

```python
>>> boost_histogram.__version__, mplhep.__version__
('0.8.0', '0.1.22')
```

It was discussed in boost-histogram here: scikit-hep/boost-histogram#379

And now when you ask for the `rank` of a `bh.Histogram`, you get the above warning.

https://github.com/scikit-hep/boost-histogram/blob/f8b15b9f21f94691f5f4151cf800b29dc2688d68/src/boost_histogram/_internal/hist.py#L501-L508

I think this is where mplhep calls it:

https://github.com/scikit-hep/mplhep/blob/6b04c756f0429af60b5815fc40c9bd5b33480ab9/mplhep/plot.py#L104-L108

Personally, I use `len(array.shape)` because this _always_ works. It dates back to antiquity, though `array.ndim` is pretty old, too:

```python
>>> # This is a sandbox; not the version of NumPy I really use!
>>> numpy.__version__
'1.10.4'
>>> len(array.shape)
3
>>> array.ndim
3
>>> array.rank
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'numpy.ndarray' object has no attribute 'rank'
```

**Comment by henryiii** [comment]
I would like to work on the interface from boost-histogram and hist; it should accept either one, it should work for 2D plots, and it should keep extra information like the title/name from Hist. @LovelyBuggies and I can prepare a PR in the coming week, I think.

**Comment by andrzejnovak** [comment]
I pushed a quick fix for that and `hist2dplot` not taking bh since it seems time-sensitive for pyhep. @henryiii I'll leave the rest of the interfacing to you. I like the idea of automatic titles when available.

**Comment by henryiii** [comment]
Perfect!
