### ISSUE TITLE
ATLAS style axis labels incorrect

### ISSUE THREAD

**Issue by Popinaodude** [scikit-hep/mplhep#168]
Axis labels in ATLAS style are much too large and positions incorrect. Here are the options I made to fix:
``
    plt.style.use([hep.style.ATLAS,
                   {'axes.labelsize': 20},
                   {'axes.labelpad': 20},
                   {'axes.titlelocation': 'right'},
                   ])
``
Incidentally the  `{'axes.titlelocation': 'right'}` doesn't seem to change anything, and neither does `plt.xlabel(r"xlabel", ha='right')`. I'm not sure if that's an issue with mplhep or matplotlib

**Comment by andrzejnovak** [comment]
Welcome @Popinaodude could you make a PR with the style changes? @kratsg does this look ok to you since it's your work originally?

The legend position is mpl related issue. We fixed it in next release. mplhep has a helper function for it for now  `mplhep.r_align()`

**Comment by kratsg** [comment]
labelsizes are `30` by default in ATLAS (I did the conversion from the ATLAS style guide to the matplotlib). For reference

[ATLAS dictates](https://twiki.cern.ch/twiki/bin/view/AtlasProtected/PubComPlotStyle#Plot_size):
- Rectangular plot: 800x600 px
- Square plot: 600x600 px

Since the smallest dimension is 600px for plots, and the font default is 42 (font choice=4, precision=2), this means that the text size in ATLAS (set to 0.05) will be a fraction of the pad size: 600*0.05 = 30.

**Comment by Popinaodude** [comment]
Perhaps it's a problem on my end, but here's the output for the same histogram at label and pad size 30 and 20 respectively:

![testplot_nofix](https://user-images.githubusercontent.com/20911987/88566063-61bb6c00-d02d-11ea-9b6b-c6a2b8b451a7.png)
![testplot_fixedstyle](https://user-images.githubusercontent.com/20911987/88566123-7b5cb380-d02d-11ea-88af-9cc55b4385c2.png)

**Comment by kratsg** [comment]
@andrzejnovak is the specification in mplhep meant to be in points or pixels? If we follow atlas style, then it should be 23/24pt, or 30 pixels.

**Comment by andrzejnovak** [comment]
@kratsg it should be in points. The labels do look a tad large to me, but if the current numbers are what the style guide dictates we should keep it.

@Popinaodude you've found the correct way to overwrite the default settings. If you have mpl 3.3+ there are two new rcParams
```
#xaxis.labellocation: center  # alignment of the xaxis label: {left, right, center}
#yaxis.labellocation: center  # alignment of the yaxis label: {bottom, top, center}
```
We should probably add these to the `mplhep` styles I think both ATLAS and CMS use the "right" aligned label position. Unsure about LHCb

[1] 
![image](https://user-images.githubusercontent.com/13226500/88777067-17e69900-d187-11ea-9bdb-9f62d74c6121.png)

**Comment by kratsg** [comment]
the style guide dictates 30 pixels.

**Comment by andrzejnovak** [comment]
Ok, it should be scaled down then.

**Comment by andrzejnovak** [comment]
@kratsg I can make a PR, does this affect other font size settings?

**Comment by kratsg** [comment]
> @kratsg I can make a PR, does this affect other font size settings?

Maybe. I assumed everything was pixels, but I guess mpl uses points by default which I didn't realize.

**Comment by andrzejnovak** [comment]
```@@ -12 +12 @@ ATLAS = {
-    "font.size": 18,
+    "font.size": 22,
@@ -23,2 +23,2 @@ ATLAS = {
-    "axes.labelsize": 30,
-    "axes.labelpad": 30,
+    "axes.labelsize": 24,
+    "axes.labelpad": 24,
@@ -26 +26 @@ ATLAS = {
-    "xtick.labelsize": 19,
+    "xtick.labelsize": 14,
@@ -32 +32 @@ ATLAS = {
-    "ytick.labelsize": 19,
+    "ytick.labelsize": 14,
```
From a cursory look, these should get changed if they were in px, to pts and get the following proportions 
![image](https://user-images.githubusercontent.com/13226500/88813379-2352b800-d1b9-11ea-8816-e136a5b40796.png)
