### ISSUE TITLE
Altair dependency

### ISSUE THREAD

**Issue by andrzejnovak** [scikit-hep/mplhep#17]
Installing `0.0.17` results shows the following error
```
ERROR: altair 3.2.0 requires entrypoints, which is not installed.
ERROR: altair 3.2.0 requires jinja2, which is not installed.
ERROR: altair 3.2.0 requires jsonschema, which is not installed.
```
I was not aware of altair dependency. @matthewfeickert Do you have an idea where this could have been introduced?

**Comment by matthewfeickert** [comment]
@andrzejnovak This got resolved?

**Comment by andrzejnovak** [comment]
I am not longer seeing it /shrug
