### ISSUE TITLE
ATLAS style susceptible to matplotlib math font bugs

### ISSUE THREAD

**Issue by matthewfeickert** [scikit-hep/mplhep#178]
@andrzejnovak I know that you're already aware of this, as you were the one to open up the `matplotlib` issue https://github.com/matplotlib/matplotlib/issues/14829, but the example that you reported there affects ATLAS style as can be seen here:

```python
import numpy as np
import matplotlib.pyplot as plt
import mplhep


def make_plot(title=None):
    fig, ax = plt.subplots()
    x = np.linspace(0, 10, 101)
    y = np.square(x)
    ax.plot(x, y)
    ax.semilogy()

    ax.set_xlabel("$x$")
    ax.set_ylabel("$x^2$")
    if title is not None:
        ax.set_title(title)

    return fig, ax


def main():
    image_types = ["pdf", "png"]
    fig, ax = make_plot("Default matplotlib settings")

    for type in image_types:
        fig.savefig(f"default.{type}")

    plt.style.use(mplhep.style.ATLAS)
    fig, ax = make_plot("mplhep ATLAS style")
    for type in image_types:
        fig.savefig(f"ATLAS_style.{type}")

    plt.style.use(mplhep.style.CMS)
    fig, ax = make_plot("mplhep CMS style")
    for type in image_types:
        fig.savefig(f"CMS_style.{type}")


if __name__ == "__main__":
    main()
```

which produces, along with the known font failure warnings,

```
Font 'default' does not have a glyph for '-' [U+2212], substituting with a dummy symbol.
Font 'default' does not have a glyph for '-' [U+2212], substituting with a dummy symbol.
Font 'default' does not have a glyph for '-' [U+2212], substituting with a dummy symbol.
Font 'default' does not have a glyph for '-' [U+2212], substituting with a dummy symbol.
Font 'default' does not have a glyph for '-' [U+2212], substituting with a dummy symbol.
Font 'default' does not have a glyph for '-' [U+2212], substituting with a dummy symbol.
Font 'default' does not have a glyph for '-' [U+2212], substituting with a dummy symbol.
Font 'default' does not have a glyph for '-' [U+2212], substituting with a dummy symbol.
findfont: Font family ['cursive'] not found. Falling back to DejaVu Sans.
'texgyreheros-regular.otf' can not be subsetted into a Type 3 font. The entire font will be embedded in the output.
```

the plots `default.png`

![default](https://user-images.githubusercontent.com/5142394/90967453-16b63c80-e4a5-11ea-9c76-5ad579d8aad7.png)

`ATLAS_style.png`

![ATLAS_style](https://user-images.githubusercontent.com/5142394/90967454-1b7af080-e4a5-11ea-8273-8f12df24f70d.png)

and `CMS_style.png`

![CMS_style](https://user-images.githubusercontent.com/5142394/90967474-639a1300-e4a5-11ea-84db-b1a0b937e077.png)

As it might take some noise on https://github.com/matplotlib/matplotlib/issues/14829 to get that addressed is it possible to change the fonts in 

https://github.com/scikit-hep/mplhep/blob/33add63905896d0d6f7fd0a802ab3bae571c8f6a/mplhep/styles_atlas.py#L4-L17

to something less "correct" but at least renders?

**Comment by kratsg** [comment]
> I have suggested appending this to the list in the past, but @kratsg has a preference for not having Helvetica failing loudly.

Not sure what you mean by this. But we should really adhere to the ATLAS styleguide. Nobody's going to know that the font is different so obviously unless they're a font designer, but I don't think it's right to force a font that is not recommended by the official pubcom.

**Comment by andrzejnovak** [comment]
@matthewfeickert are you planning to come back to this or can I close it?

**Comment by matthewfeickert** [comment]
> @matthewfeickert are you planning to come back to this or can I close it?

I am planning on coming back to it, but this can be closed for now as it isn't a `mplhep` bug.

**Comment by matthewfeickert** [comment]
For the record, the fix was incredibly easy and just total oversight on my part. I had forgotten that `matplotlib` has a font cache and [`matplotlib.font_manager`](https://matplotlib.org/3.3.2/api/font_manager_api.html). So all that is needed is

```python
import matplotlib.font_manager
matplotlib.font_manager._rebuild()
```

as I apparently had the correct fonts.

**Comment by matthewfeickert** [comment]
Actually, the fix ended up being more subtle as just the font list cache. For the Stack Ovreflow question "[matplotlib mathtext font warning: Font 'default' does not have a glyph](https://stackoverflow.com/questions/65625150/matplotlib-mathtext-font-warning-font-default-does-not-have-a-glyph)" I had more than just `fontlist-v330.json` in the `matplotlib` cache

```
$ ls -htra ~/.cache/matplotlib/
..  tex.cache  fontlist-v330.json  .
```

so rebuilding the font list cache with

```python
import matplotlib.font_manager
matplotlib.font_manager._rebuild()
```

or 

```
rm ~/.cache/matplotlib/fontlist-v330.json
```

wasn't sufficient. Instead [the entire `matplotlib` cache needs to be updated](https://github.com/matplotlib/matplotlib/issues/17585#issuecomment-653060005), which is most easily done with

```
rm ~/.cache/matplotlib/*
```
