### ISSUE TITLE
Install .mplstyles files 

### ISSUE THREAD

**Issue by andrewfowlie** [scikit-hep/mplhep#19]
Can the setup.py copy the .mplstyle files to the appropriate location automatically (I.e., the user directory where he other styles in plt.style.available are stored)? 

I would like this so that the styles are treated in an equal footing with all the other ones. 

I’m actually a bit confused about the duplication of mpl styles - we have the .mplstyle files and dictionaries containing similar (possibly identical) information.

**Comment by andrzejnovak** [comment]
@andrewfowlie  We used to have it setup that way, but it's not entirely kosher to directly modify another package's files. The fact that the `.mplstyle` files exist is an atavism of that approach. There's a helper function to copy the style files to mpl directory here https://github.com/scikit-hep/mplhep/blob/master/mplhep/tools.py#L6 though the styles may not be 100% up to date.

**Comment by andrewfowlie** [comment]
I see - I didn’t realise that the mplstyles files had that status. The preferred methods for distributing and installing rc settings isn’t that clear from the matplotlib docs. 

For the specific case in mind I wanted to call plt.style.use with a string rather than a dict and have access to a list of all available styles. Your copying functions will help.

**Comment by andrzejnovak** [comment]
I don't think that's something originally thought of at mpl. What benefit do you get by calling say `plt.style.use("ROOT")` as opposed to `plt.style.use(hep.style.ROOT)` ?

**Comment by andrewfowlie** [comment]
I have another code that plots some statistical quantities. The theme - default, classic, etc - is set by a string in a config file or selected through a GUI from the plt.styles.available list. Nothing important and unlikely to be a common problem :D
