### ISSUE TITLE
Setting histplot color when specifying yerr or w2

### ISSUE THREAD

**Issue by JHiltbrand** [scikit-hep/mplhep#190]
It seems that when one requests yerr or w2 when calling histplot for a 'step' histtype, the user no longer can specify the color of the histogram. This is because the color='blah' argument from the histplot call gets passed in the kwargs in the [call to errorbar](https://github.com/scikit-hep/mplhep/blob/master/mplhep/plot.py#L290-L297), while at the same time `color=_s.get_color()` is passed explicitly to errorbar. Thus a conflict arises and the user receives the error: `TypeError: errorbar() got multiple values for keyword argument 'color'`

**Comment by andrzejnovak** [comment]
Thanks a lot for the bug report. Should be fixed now.
