### ISSUE TITLE
How to style plots with 14 TeV and pileup in the header?

### ISSUE THREAD

**Issue by dildick** [scikit-hep/mplhep#197]
Suppose I want to make plots for Phase-2 and I want to write the header as "14 TeV (200 PU)". It was the default method for the CMS Phase-2 L1-trigger TDR IIRC. Is this option already included in mplhep?

**Comment by andrzejnovak** [comment]
Hi @dildick you can either use the kwargs `rlabel`/`llabel` within the `mplhep.cms.label()` to overwrite the defaults
e.g 
```
mplhep.cms.label(rlabel="14 TeV (200 PU)")
```
or you can separately use the following to set the left and right text separately
```
mplhep.cms.text("Phase2 Studies")
mplhep.cms.lumitext("14 TeV (200 PU)")
```
