### ISSUE TITLE
Aspect-ratio flattening behaviour when using `hist2dplot` inside loop

### ISSUE THREAD

**Issue by romanovzky** [scikit-hep/mplhep#198]
Hi there,
I'm using `hist2dplot` to produce some 2d histograms over a dataframe. The code is something like this
```python
for feature in features:
    if feature == "nconst":
        continue
    feat1 = "nconst"
    feat2 = feature

    hist, xedged, yedges = np.histogram2d(
        data[feat1].values,
        data[feat2].values,
        weights=data.jetwt,
        bins=25,
        density=True,
    )
    plt.clf()
    plt.cla()
    plt.title(f"2D Histogram {feat1}-{feat2}")
    hep.hist2dplot(hist, xedged, yedges)
    plt.xlabel(feat1)
    plt.ylabel(feat2)
    plt.tight_layout()
    plt.savefig(f"plots/2d_hist_{feat1}_vs_{feat2}.png")
```
However, the produced images are "shrinking". I.e., the aspect ratio is getting wider, with the histogram cells becoming progressively flatter

![image](https://user-images.githubusercontent.com/7794475/94672080-a9e85a80-030c-11eb-85ae-c9f0532682fd.png)

Is this a known bug? How do I debug further?

**Comment by romanovzky** [comment]
Furthermore, the problem gets more verbose if we do not call `plt.clf()`, in that case the plots become wider with a blank margin and it produces the following `Exception`:
```python
ValueError: Image size of 65638x648 pixels is too large. It must be less than 2^16 in each direction.
```
It seems that something is being incremented and persisted across plots, which shouldn't.

**Comment by andrzejnovak** [comment]
A cbar is actually an axes object, like a pad in root. The issue is that clf/cla clean the current axis/figure of artists but don't reset to a blank state.

What you want is to create a new figure in each loop via `fig, ax = plt.subplots` This should be enough though for more control you can also pass the axes object to histology directly

**Comment by romanovzky** [comment]
@andrzejnovak cheers, that has indeed solved the problem! I was also noticing the problem went away if I set `cbar=False`, for the reason you say. Thanks!
