### ISSUE TITLE
Documentation improvements

### ISSUE THREAD

**Issue by DraTeots** [scikit-hep/mplhep#199]
Dear sci-kit hep community and mplhep developers. 

I really appreciate your effort and really thankful for these libraries. (You guess, a bold BUT now). BUT none of the fixed or further development can make an improvement and worth as much as a sane and clear documentation at this stage. Please don't follow this disastrous path of HENP software development: "We will do the perfect library first, and then add some documentation later". 

I spent some time now tying to move my work to hist, mplhep, boost histograms from ROOT. And enormous amount of time was spent on a small stupid simple things that could be in the documentation but they are not. And trust me, none of the issues in the bug tracker would make me as happy as some more informative documentation. 

Going back to this ticket, please can you clearly add to the documentation that when you use 

histtype == "step" -  ax.step is used under the hood
histtype='fill' - ax.fill_between  is used under the hood
histtype='errorbar' - ax.plot  is used under the hood
As one has to figure out what kw_args available, which you kindly pass to the underlying method. 

So other users could just use this information and spend their time working and not reading mplhep code.

**Comment by andrzejnovak** [comment]
Cheers for the reminder, the docstrings actually needs to be updated for the new return types which should make it more obvious.

**Comment by andrzejnovak** [comment]
Fixed in #200
