### ISSUE TITLE
Cannot plot boost-histogram histogram when using a storage

### ISSUE THREAD

**Issue by KeanuGh** [scikit-hep/mplhep#205]
Using an accumulator storage in histogram when plotting returns an error. This makes it very difficult to plot sumw2 errors

code:

```
import mplhep as hep
import boost_histogram as bh

# Make 1-d histogram with 5 logarithmic bins from 1e0 to 1e5
h = bh.Histogram(
    bh.axis.Regular(5, 1e0, 1e5, metadata="x", transform=bh.axis.transform.log),
    storage=bh.storage.Weight(),
)

# Fill histogram with numbers
x = (2e0, 2e1, 2e2, 2e3, 2e4)
h.fill(x, weight=2)

hep.histplot(h)
```

error:
```
 File "C:\Users\user\anaconda3\envs\myenv\lib\site-packages\mplhep\plot.py", line 132, in histplot
    h = np.asarray(h).astype(float)
TypeError: Cannot cast array from dtype([('value', '<f8'), ('variance', '<f8')]) to dtype('float64') according to the rule 'unsafe'
```

**Comment by Popinaodude** [comment]
The way that I've managed to get it to work is by doing ```hep.histplot(h.view().value, bins=h.axes[0].edges)``` which doesn't feel very pythonic

**Comment by andrzejnovak** [comment]
@henryiii

**Comment by henryiii** [comment]
This is one of the reasons we need https://github.com/scikit-hep/boost-histogram/issues/423 - I'm hoping to make progress on that issue next week, @HDembinski had some good suggestions that I can build a new proposal on.

**Comment by andrzejnovak** [comment]
Thanks @henryiii I figured it was something like this. @Popinaodude we'll get this working when the underlying API is decided

**Comment by andrzejnovak** [comment]
@KeanuGh seems fixed (I've added `plt.semilogx()` to your example)
![image](https://user-images.githubusercontent.com/13226500/119228613-10c4b900-bb14-11eb-8798-083f88f862f2.png)
