### ISSUE TITLE
Allow for histoplot to accept a list of hist.Hist.hist objects

### ISSUE THREAD

**Issue by matthewfeickert** [scikit-hep/mplhep#212]
It would be nice if `mplhep.histoplot` could accept a list of `hist` objects. At the moment it can accept a list of NumPy arrays, or a single `hist` object, but not a list.

## Minimal Failing Example

```
# requirements.txt 
mplhep==0.2.2
hist~=2.0.1
```

```python
#issue.py
import sys
import numpy as np
import hist
from hist import Hist
import matplotlib.pyplot as plt
import mplhep


def numpy_to_hist(np_hist, name):
    values, edges = np_hist
    _hist = Hist(
        hist.axis.Regular(len(edges) - 1, edges[0], edges[-1], name=name),
        storage=hist.storage.Double(),
    )
    _hist[:] = values
    return _hist


def main(input):
    np.random.seed(0)
    n_signal = 1000
    n_background = 10 * n_signal
    signal_sample = np.random.normal(loc=5, scale=2, size=n_signal)
    # (b - a) * random_sample() + a # a=0, b=10
    background_sample = 10 * np.random.random_sample(n_background)

    _width = 0.2
    bins = np.arange(0, 10 + _width, +_width)
    signal_hist = np.histogram(signal_sample, bins=bins)
    background_hist = np.histogram(background_sample, bins=bins)

    hists = [
        numpy_to_hist(h, name)
        for h, name in zip([background_hist, signal_hist], ["background", "signal"])
    ]

    fig, ax = plt.subplots()
    if input[-1] == "pass":
        np_hists = [h[0] for h in [background_hist, signal_hist]]
        mplhep.histplot(np_hists, bins=signal_hist[1], stack=True)
        fig.savefig("pass.png")

        # Can take a single hist
        fig, ax = plt.subplots()
        mplhep.histplot(hists[1])
        fig.savefig("signal_hist.png")
    else:
        # Can't take a list of hists
        mplhep.histplot(hists, stack=True)


if __name__ == "__main__":
    main(input=sys.argv)
```

Running the above in a virtual environment made form installing the `requirements.txt` gives the following error:

```pytb
$ python issue.py 
TypeError: float() argument must be a string or a number, not 'Hist'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "issue.py", line 53, in <module>
    main(input=sys.argv)
  File "issue.py", line 49, in main
    mplhep.histplot(hists, stack=True)
  File "/home/feickert/.venvs/mplhep-issue/lib/python3.7/site-packages/mplhep/plot.py", line 132, in histplot
    h = np.asarray(h).astype(float)
  File "/home/feickert/.venvs/mplhep-issue/lib/python3.7/site-packages/numpy/core/_asarray.py", line 83, in asarray
    return array(a, dtype, copy=False, order=order)
ValueError: setting an array element with a sequence.
```

but it would be nice to get similar behavior as to what happens with

```
$ python issue.py pass
```
`pass.png`
![pass](https://user-images.githubusercontent.com/5142394/97816851-01584e00-1c5e-11eb-9783-9f13bf4aa3e4.png)
`signal_hist.png`
![signal_hist](https://user-images.githubusercontent.com/5142394/97816855-05846b80-1c5e-11eb-9873-20e4e74f3a86.png)

**Comment by andrzejnovak** [comment]
Happening in #210, right now it's limited to only work if bins are the same for all objects. Do you think there's use case for it to also work for histograms with different binning? It would require some refactoring but could be done, I'm just not sure how often that can happen

**Comment by matthewfeickert** [comment]
> Do you think there's use case for it to also work for histograms with different binning? It would require some refactoring but could be done, I'm just not sure how often that can happen

@andrzejnovak No, I personally don't really see the need for this. I mainly want this to be able to make stacked histogram plots very easily so I'm going to be requiring uniform bins for them all anyway.

**Comment by matthewfeickert** [comment]
@andrzejnovak Did PR #210 close this out? Or is there more work to be done here?

**Comment by andrzejnovak** [comment]
@matthewfeickert can you take a look if https://pypi.org/project/mplhep/0.2.6/ works for you?
