### ISSUE TITLE
Add convince wrapper function mplhep.set_style to set experiment style

### ISSUE THREAD

**Issue by matthewfeickert** [scikit-hep/mplhep#213]
It would be nice if there was a convince wrapper function named something like `mplhep.set_style` that wrapped `plt.style.use` to allow for setting the `mplhep` plot style through both an `mplhep` style `dict` as well as a string alias. I've [implemented this in `heputils`](https://github.com/matthewfeickert/heputils/pull/7) [![Binder](https://mybinder.org/badge_logo.svg)](https://mybinder.org/v2/gh/matthewfeickert/heputils/HEAD?urlpath=lab/tree/examples/dev-example.ipynb) to allow for the following API

```python
import heputils
import mplhep
heputils.plot.set_style("ATLAS") # string alias
heputils.plot.set_style(mplhep.style.CMS) # style dict
```

It would be nice to impliment it here to allow for

```python
import mplhep
mplhep.set_style("ATLAS") # string alias
mplhep.set_style(mplhep.style.CMS) # style dict
```

If you agree @andrzejnovak I can open a PR that adds this.

**Comment by andrzejnovak** [comment]
That's a great idea!
