### ISSUE TITLE
bug: Fira Sans missing from styles module

### ISSUE THREAD

**Issue by matthewfeickert** [scikit-hep/mplhep#217]
I'm noticing that I'm seeing some of the font styles not being found correctly. For example, using the original `matplotlib.pyplot` API:

```python
>>> import mplhep
>>> import matplotlib.pyplot as plt
>>> plt.style.use(mplhep.style.fira)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'mplhep.styles' has no attribute 'fira'
```

Tab completing in the REPL shows

```python
>>> mplhep.style.
mplhep.style.ALICE       mplhep.style.CMS         mplhep.style.LHCb        mplhep.style.ROOT        mplhep.style.fabiola     mplhep.style.plt_style   mplhep.style.sys         
mplhep.style.ATLAS       mplhep.style.CMSTex      mplhep.style.LHCbTex     mplhep.style.ROOTTex     mplhep.style.firamath
```

From the same Issue:

> I must have removed fira when making other changes. I suggest you ignore it in this PR and I'll add it back later. - @andrzejnovak 

_Originally posted by @matthewfeickert in https://github.com/scikit-hep/mplhep/pull/216#r516158743_

**Comment by andrzejnovak** [comment]
Fixed in #219
