### ISSUE TITLE
Automatically zero the ylim

### ISSUE THREAD

**Issue by aperloff** [scikit-hep/mplhep#22]
When plotting in matplotlib, if a plot has some entries at zero and the others positive, then the zero point will be shown on the y-axis. The default style in matplotlib is to set the minimum value on the y-axis to be slightly below zero, I presume to be better able to see which markers or points on the line are at zero. However, the CMS style is to set ymin=0. It would be nice if mplhep automatically zeroed the y-axis, unless specified by the user or there are negative values.

**Comment by andrzejnovak** [comment]
Can you elaborate on what the actual functionality should be? I can include a limit setter in the `mplhep` plotting functions i,e. `histplot()` would default to `ymin=0`, but it's not possible to adjust that for `mpl` functions like `plt.plot()` or `plt.hist()`

**Comment by aperloff** [comment]
A helper function then? Something like reset_zero(ax)? It mostly just took me by surprise and was something I had to figure out in order to match the CMS style.

**Comment by andrzejnovak** [comment]
I could add it, but is it really saving time over `plt.ylim(0, plt.ylim[-1])` or `ax.set_ylim(0, ax.get_ylim()[-1])`, both or which pop up real quick on google.

**Comment by aperloff** [comment]
Probably not. It would just be easier to remember and less googling.

**Comment by andrzejnovak** [comment]
Well if you don't know either, you have to look up both and matplotlib will show up quicker. I'm gonna leave this open for a while if anyone chimes in.

I could maybe add it to the `cms_magic()` to adjust the lower limit if not data/errors are actually going below 0. I think that would be a resonable compromise and work in most cases, without making stuff more confusing.
