### ISSUE TITLE
<experiment>.label should take 'italic', make _exp_label public

### ISSUE THREAD

**Issue by KeanuGh** [scikit-hep/mplhep#220]
I'm trying to set up my plot title to look like this:
`hep.atlas.label(data=True, paper=True, italic=?,
                llabel='internal', rlabel=r"$W^-\rightarrow\tau\bar{\nu}$ mass slices")`

I'd like the ATLAS label and 'internal' to be italicised but not the right label. I've tried the following:
`italic=True`, `italic=(True, False)`, `italic=((True, True), False)` but all three raise the following error:
`TypeError: _exp_label() got multiple values for keyword argument 'italic'`

The documentation says "italic ((bool, bool), optional) – Tuple of bools to switch which label is italicized" but I'm not sure how this is supposed to be implemented?

**Comment by andrzejnovak** [comment]
Thanks for pointing that out! This is an error in the somewhat automated docs. But there's really no reason I think to not have the underlying class be public and to allow setting italics manually. I'll fix this at some point. 

For now you could just use the private base class
```
import mplhep as hep
from mplhep import label as label_base

hep.histplot([1,2,3])
label_base._exp_label(exp="ATLAS", italic=(True, True))
```

**Comment by KeanuGh** [comment]
Ah thank you that works! My IDE complains about accessing a protected member but I guess it'll have to deal with that for now
