### ISSUE TITLE
Linestyle in histplot

### ISSUE THREAD

**Issue by romanovzky** [scikit-hep/mplhep#233]
Hi there, how do I set the linestyle in histplot? I tried to pass it as a `kwarg`, but got
```
TypeError: errorbar() got multiple values for keyword argument 'linestyle'
```
I'm trying to plot histograms of the same variable produced through different methods and I'd like to be able to set the same colour, but different linestyles for each case.

Cheers

**Comment by andrzejnovak** [comment]
@romanovzky It sounds like you have `histtype='errorbar'` on, which uses [errorbar](https://matplotlib.org/3.1.1/api/_as_gen/matplotlib.pyplot.errorbar.html) underneath which doesn't have a `ls` kwarg. If you are making expecting a "skyline" plot pass `histtype='step'`.
