### ISSUE TITLE
year is not documented correctly for experiment labels

### ISSUE THREAD

**Issue by kratsg** [scikit-hep/mplhep#237]
`year` for all experiment labels (e.g via the label base) is determined by stringifying it: https://github.com/scikit-hep/mplhep/blob/431b4b0b54867f3ddb6bea11da75a2fca1ab5106/src/mplhep/label.py#L287-L291

there's two issues:
* the year is specified as an integer, which means in order to turn it off, you specify `year=""` which is not so obvious
* the year is specified as optional with a default of 2017, instead of perhaps the default being not to include the year [I've rarely seen the year be included on most of these plots]

**Comment by andrzejnovak** [comment]
Good point.
