### ISSUE TITLE
ATLAS experiment labels have the wrong positioning/ordering?

### ISSUE THREAD

**Issue by kratsg** [scikit-hep/mplhep#238]
<img width="339" alt="Screen Shot 2021-01-08 at 8 26 13 AM" src="https://user-images.githubusercontent.com/761483/104020432-38316f80-518b-11eb-8e88-6f2d9e03c535.png">

in ATLAS, we follow this sort of style for positioning the text for the labels. That is `llabel` is to the right of the experiment name and `rlabel` is the next line below it. The default in mplhep doesn't allow for moving the llabel and rlabel necessarily, so there's not a lot we can do here?

<img width="688" alt="Screen Shot 2021-01-08 at 8 27 21 AM" src="https://user-images.githubusercontent.com/761483/104020560-6911a480-518b-11eb-96cc-96bfcefd2fc3.png">

**Comment by kratsg** [comment]
The following code helps get pretty close:

```
text, suffix = hep.atlas.text(ax=ax, loc=2, text="Internal")
bbox = text.get_window_extent(renderer=fig.canvas.get_renderer())
bbox_axes = matplotlib.transforms.Bbox(suffix.get_transform().inverted().transform(bbox))
suffix.set_position((text.get_position()[0] + bbox_axes.width + 0.02, text.get_position()[1] + bbox_axes.height))
suffix.set_fontsize(text.get_fontsize())
```

<img width="333" alt="Screen Shot 2021-01-08 at 8 51 59 AM" src="https://user-images.githubusercontent.com/761483/104022813-c9eeac00-518e-11eb-960c-ebf2fbe8663a.png">

**Comment by kratsg** [comment]
```
label = hep.label.ExpSuffix(*suffix.get_position(),
                            text=r"$\sqrt{s} = \mathrm{13\ TeV}, 139\ \mathrm{fb}^{-1}$",
                            transform=suffix.get_transform(),
                            ha=suffix.get_ha(),
                            va=suffix.get_va(),
                            fontsize=suffix.get_fontsize(),
                            fontname=suffix.get_fontname(),
                            fontstyle="normal")
ax._add_text(label)
```

this addition will get the following as well

<img width="306" alt="Screen Shot 2021-01-08 at 9 06 13 AM" src="https://user-images.githubusercontent.com/761483/104024240-d4aa4080-5190-11eb-8f34-305a7cefc884.png">

**Comment by andrzejnovak** [comment]
There's a `loc` keyword already doing several configs, it should be possible add one, where `rlabel` is under `llabel` like this

**Comment by andrzejnovak** [comment]
Close via #282. `exp_label(..., loc=4)`
