### ISSUE TITLE
Add custom Font Manager to download fonts

### ISSUE THREAD

**Issue by matthewfeickert** [scikit-hep/mplhep#241]
Following [discussion in Issue #240](https://github.com/scikit-hep/mplhep/issues/240#issuecomment-758098060), it seems there is agreement that adding a [custom Font Manager similar to how Colin Carroll has done in `ridge-map`](https://github.com/ColCarroll/ridge_map/blob/e7331d5038e3dee99aa061d562a8661cac6b5d62/ridge_map/ridge_map.py#L16-L53) (thanks @ColCarroll!) would be a useful thing for `mplhep` and sidesteps most of the need to vendor fonts with the library.

It should be relatively straightforward to adopt what Colin setup in `ridge-map` for `mplhep`'s needs.

(For posterity: [The Tweet that directed us to this information](https://twitter.com/colindcarroll/status/1348434308701315073?s=20))

**Comment by andrzejnovak** [comment]
Close via #282 - fonts in a separate package, util out of scope now
