### ISSUE TITLE
Problems with axis sizing for mplhep v0.2.10+

### ISSUE THREAD

**Issue by matthewfeickert** [scikit-hep/mplhep#242]
Cross post of https://github.com/matthewfeickert/heputils/issues/41

---

In PR #239 the ATLAS style figure defaults were updated and this change was released in mplhep `v0.2.10`. This is apparently having some extreme effects (c.f. https://github.com/matthewfeickert/heputils/issues/41 for more examples)

## Reproducible Example

In a clean Python 3 virtual environment the following

```python
# example.py
import uproot4 as uproot
from heputils import convert
import mplhep
import matplotlib.pyplot as plt


def main():
    root_file = uproot.open("example.root")
    root_hists = [convert.uproot_to_hist(root_file[key]) for key in root_file.keys()]
    data_hist = root_hists[-1]
    simulation_hists = root_hists[:-1]

    mplhep.set_style("ATLAS")
    fig, ax = plt.subplots()
    mplhep.histplot(simulation_hists[0], histtype="fill", ax=ax)
    ax.set_xlabel(r"$X$ Mass [$\mathrm{GeV}$]")
    ax.set_ylabel("Count")

    fig.savefig(f"mplhep_v{mplhep.__version__}_example.png")


if __name__ == "__main__":
    main()
```

```
$ python -m pip install --quiet heputils
$ pip list
Package         Version
--------------- ---------
awkward         1.0.2
awkward0        0.15.2
awkward1        1.0.0
boost-histogram 0.11.1
cachetools      4.2.0
certifi         2020.12.5
chardet         4.0.0
click           7.1.2
cycler          0.10.0
future          0.18.2
heputils        0.0.4
hist            2.0.1
histoprint      1.5.2
idna            2.10
kiwisolver      1.3.1
matplotlib      3.3.3
mplhep          0.2.10
numpy           1.19.5
packaging       20.8
Pillow          8.1.0
pip             20.3.3
pyparsing       2.4.7
python-dateutil 2.8.1
requests        2.25.1
scipy           1.6.0
setuptools      51.1.2
six             1.15.0
uncertainties   3.1.5
uproot          4.0.0
uproot3         3.14.2
uproot3-methods 0.10.0
uproot4         4.0.0
urllib3         1.26.2
wheel           0.36.2
$ curl -sL https://raw.githubusercontent.com/matthewfeickert/heputils/master/tests/example_files.py | python
$ file example.root 
example.root: ROOT file Version 1061800 (Compression: 256)
$ python example.py
$ pip install --upgrade "mplhep<0.2.10"
$ python -m pip list | grep mplhep
mplhep                 0.2.9
$ python example.py
```

produces

| `mplhep_v0.2.9_example.png` | `mplhep_v0.2.10_example.png` |
| -- | -- |
| ![mplhep_v0 2 9_example](https://user-images.githubusercontent.com/5142394/104252113-dac14b00-5436-11eb-8ebd-5a39fca1539f.png) | ![mplhep_v0 2 10_example](https://user-images.githubusercontent.com/5142394/104252115-dc8b0e80-5436-11eb-8621-f0c6466a4b1a.png) |

cc @andrzejnovak and @kratsg

**Comment by kratsg** [comment]
The axes labels are meant to be much bigger than they are right now (this all got fixed up and I measured all the sizes based off one of the default ATLAS plots). One nice feature is that if you find it slightly too large, you can change the default font size and all other features will scale respectively.

**Comment by matthewfeickert** [comment]
> The axes labels are meant to be much bigger than they are right now (this all got fixed up and I measured all the sizes based off one of the default ATLAS plots). One nice feature is that if you find it slightly too large, you can change the default font size and all other features will scale respectively.

Ah is this part of the "fix up" that you mentioned you were going to contribute back to `mplhep`?

**Comment by kratsg** [comment]
> Ah is this part of the "fix up" that you mentioned in chat you were going to contribute back to `mplhep`?

This is already fixed. The axes labels are bigger now, which was a common issue with the older ATLAS style. The newer one looks more correct in 0.2.10.

**Comment by matthewfeickert** [comment]
> This is already fixed. The axes labels are bigger now, which was a common issue with the older ATLAS style. The newer one looks more correct in 0.2.10.

The `v0.2.10` horizontal axis looks terrible though. What is your recommendation for how to treat the example I gave? Sensible defaults are important, so is there a way to safeguard things looking so bad?

**Comment by kratsg** [comment]
> The `v0.2.10` horizontal axis looks terrible though. What is your recommendation for how to treat the example I gave? Sensible defaults are important, so is there a way to safeguard things looking so bad?

that's actually following the atlas style guide... so 🤷‍♂️

The `axes.formatter.limits` are set to (-2, 4) [https://matplotlib.org/3.1.1/api/ticker_api.html#matplotlib.ticker.ScalarFormatter] which means values < 1e-2 or > 1e+4 will switch the x-axis to that. The default is `axes.formatter.limits: -5, 6` but this wasn't following atlas style. I guess your concern is just about the scientific notation?

**Comment by matthewfeickert** [comment]
> that's actually following the atlas style guide... so 

Yeah. Le sigh. :/ Also that wasn't supposed to be a dig at your work, just the current result. 

> 
> The `axes.formatter.limits` are set to (-2, 4) [https://matplotlib.org/3.1.1/api/ticker_api.html#matplotlib.ticker.ScalarFormatter] which means values < 1e-2 or > 1e+4 will switch the x-axis to that. The default is `axes.formatter.limits: -5, 6` but this wasn't following atlas style. I guess your concern is just about the scientific notation?

Partly about the scientific notation but also about where it lands on the plot (falling off below the axis and onto where the label is). Do you have suggestions on how to handle this gracefully (both in general and on the `heputils` side)? Or will the user need to define custom ticks if their spanning a range this large?

**Comment by kratsg** [comment]
> Do you have suggestions on how to handle this gracefully (both in general and on the `heputils` side)? Or will the user need to define custom ticks if their spanning a range this large?

no good solution. You have a weird situation that requires such a large range in general. For example, ATLAS will plot in units of energy which usually ranges up to 13 TeV or units of multiplicity, etc...



> Partly about the scientific notation but also about where it lands on the plot (falling off below the axis and onto where the label is).

I don't know how to fix that formatting as it doesn't seem to be matplotlib-configurable --- and you'd have to manually do it... https://stackoverflow.com/a/39622229/1532974

**Comment by andrzejnovak** [comment]
Does this leave anything unresolved on `mplhep` side? The sci notation effect is unfortunate, but I don't see what we could do about it. In fact, I am not even sure what the correct solution is, move the xlabel toward the center? Either way I think this needs to be resolved on the user side.

**Comment by matthewfeickert** [comment]
@kratsg as a follow up question on this, can you tell me what changed wrt the horiztonal axis buffers in PR #239? If I now have

```
$ cat requirements.txt 
uproot~=4.0.6
uproot3~=3.14.4
hist~=2.2.0
mplhep~=0.2.17
```

and

```python
# example.py
import matplotlib.pyplot as plt
import mplhep
import uproot


def main():
    root_file = uproot.open("example.root")
    root_hists = [root_file[key].to_hist() for key in root_file.keys()]
    data_hist = root_hists[-1]
    simulation_hists = root_hists[:-1]

    mplhep.set_style("ATLAS")
    fig, ax = plt.subplots()
    mplhep.histplot(simulation_hists[0], histtype="fill", ax=ax)
    ax.set_xlabel(r"$X$ Mass [$\mathrm{GeV}$]")
    ax.set_ylabel("Count")

    fig.savefig(f"mplhep_v{mplhep.__version__}_example.png")


if __name__ == "__main__":
    main()
```

and with the binning changed in `example_files.py` to not have the horizontal axis scale go into scientific notation, then

```
$ pip install -r requirements.txt
$ curl -sL https://raw.githubusercontent.com/matthewfeickert/heputils/master/tests/example_files.py | python
$ file example.root 
example.root: ROOT file Version 1061800 (Compression: 256)
$ python example.py
$ pip install --upgrade "mplhep<0.2.10"
$ python -m pip list | grep mplhep
mplhep                 0.2.9
$ python example.py
```

produces

| `mplhep_v0.2.9_example.png` | `mplhep_v0.2.17_example.png` |
| -- | -- |
| ![mplhep_v0 2 9_example](https://user-images.githubusercontent.com/5142394/111251328-013d6700-85dd-11eb-8da0-7fa8071d7ca0.png) | ![mplhep_v0 2 17_example](https://user-images.githubusercontent.com/5142394/111251340-04385780-85dd-11eb-83e0-a4e679b45330.png) |

Do you know what is producing the very large offsets from the edges of the histogram on the horizontal axis in the `mplhep_v0.2.17_example.png`? This doesn't seem to match any of our typical ATLAS plots. Eg. [JHEP 06 (2018) 107](https://atlas.web.cern.ch/Atlas/GROUPS/PHYSICS/PAPERS/SUSY-2016-10/) has the edges of the horiztonal axis flush with the edges of the histogram.

**Comment by matthewfeickert** [comment]
The closest I can get if I write some very crappy PyROOT (and feel embarrassed at how bad my ROOT skills are now) with `AtlasStyle.C` and  `AtlasStyle.h` in the directory

```python
# example_pyroot.py
from ROOT import TCanvas, TColor, TFile, gROOT, kFALSE, kTRUE

gROOT.LoadMacro("AtlasStyle.C")
gROOT.SetBatch(kTRUE)


def main():
    read_file = TFile.Open("example.root", "READ")
    hist_ttbar = read_file.Get("ttbar")

    canvas = TCanvas("")
    canvas.cd()

    hist_ttbar.SetStats(kFALSE)
    fill_color = TColor.GetColor("#1f77b4")
    hist_ttbar.SetFillColor(fill_color)
    hist_ttbar.GetXaxis().SetTitle("X Mass [GeV]")
    hist_ttbar.GetYaxis().SetTitle("Count")

    hist_ttbar.Draw("HIST")
    canvas.SaveAs("pyroot_example.png")


if __name__ == "__main__":
    main()
```

is if I amend ATLAS style to have `"axes.xmargin": 0.0`

```python
# example.py
import matplotlib.pyplot as plt
import mplhep
import uproot
from matplotlib.pyplot import style


def main():
    root_file = uproot.open("example.root")
    root_hists = [root_file[key].to_hist() for key in root_file.keys()]
    data_hist = root_hists[-1]
    simulation_hists = root_hists[:-1]

    mplhep.set_style("ATLAS")
    style.use({"axes.xmargin": 0.0})

    fig, ax = plt.subplots()
    mplhep.histplot(simulation_hists[0], histtype="fill", ax=ax)
    ax.set_xlabel(r"$X$ Mass [$\mathrm{GeV}$]")
    ax.set_ylabel("Count")

    fig.savefig(f"mplhep_v{mplhep.__version__}_example_revised.png")


if __name__ == "__main__":
    main()
```

| `pyroot_example.png` | `mplhep_v0.2.17_example_revised.png` |
| -- | -- |
| ![pyroot_example](https://user-images.githubusercontent.com/5142394/111258918-ede5c800-85eb-11eb-9b11-4ece1f38648b.png) | ![mplhep_v0 2 17_example_revised](https://user-images.githubusercontent.com/5142394/111258925-f0482200-85eb-11eb-974a-04047a961e5c.png) |

Thoughts? Am I doing something wrong?
