### ISSUE TITLE
[feat] Implement PlottableProtocol

### ISSUE THREAD

**Issue by andrzejnovak** [scikit-hep/mplhep#246]
- https://github.com/scikit-hep/boost-histogram/pull/476
- https://github.com/henryiii/uhi/pull/2

**Comment by henryiii** [comment]
I'm going to try to get this in very soon (will be teaching a course tomorrow, so possibly not before that), then will help get this in mplhep too!

**Comment by beojan** [comment]
I have this implemented in atlas-mpl-style [here](https://github.com/beojan/atlas-mpl/blob/master/atlas_mpl_style/uhi.py#L164) if you want to copy the implementation over. I delegate the plotting to my existing functions so it should be portable to mplhep.

**Comment by andrzejnovak** [comment]
cheers @beojan, should be helpful getting started. I was actually waiting for hist/bh to get it implemented first, so I have some objects to test it on, but it looks like that might have already happened.

On a side note I've skimmed through `atlas-mpl-style`  and it seems to target very similar use to `mplhep`. Did it somehow grow independently before `mplhep` or is there a structural reason why you preferred to have a separate package?

**Comment by beojan** [comment]
> Did it somehow grow independently before mplhep or is there a structural reason why you preferred to have a separate package?

`atlas-mpl-style` predates `mplhep` by a little over a year. It also does everything `mplhep` does and more (e.g. splitting axes for ratio plots, drawing ratio plots, drawing limit plots) so it's never made sense to refactor it to build on `mplhep`.
