### ISSUE TITLE
Y axis resizing to remove legend overlap takes ages if the y axis is set to log

### ISSUE THREAD

**Issue by bsathian** [scikit-hep/mplhep#257]
https://github.com/scikit-hep/mplhep/blob/d0248fd38b3559dee285ea2707c66f53e5725919/src/mplhep/plot.py#L600-L610

1.05 is too small a number if the y axis is set to log and the resize loop takes a long time to resize the axis. This means that the axis needs to be rescaled by a larger number in the linear domain, but still a small enough number in the log domain - like 10**(1.05). I've fixed this in a new pull request (https://github.com/scikit-hep/mplhep/pull/258)

**Comment by andrzejnovak** [comment]
Fixed in #258. Thanks again.
