### ISSUE TITLE
Subplots with 2D Histograms

### ISSUE THREAD

**Issue by cburton12** [scikit-hep/mplhep#259]
Hello,

I learned about this at PyHEP last year, and am finally getting around to using this as part of my usual plotting routine. (I really like the package so far!) Anyway, when making some 2D histograms, I noticed what I think is a bug. When making a figure with subplots containing 2D histograms, the addition of the color bar messes up the figures. Here is a short example:
```import numpy as np
import mplhep as hep
import matplotlib.pyplot as plt
hep.set_style('ATLAS')

xedges = np.arange(0, 11.5, 1.5)
yedges = [0, 2, 3, 4, 6, 7]
x = np.random.normal(5, 1.5, 100)
y = np.random.normal(4, 1, 100)
H, xedges, yedges = np.histogram2d(x, y, bins=(xedges, yedges))

fig, axs = plt.subplots(1, 2, figsize=(12, 6))
hep.hist2dplot(H, xedges, yedges, cbar=True, ax=axs[0])
hep.hist2dplot(H, xedges, yedges, cbar=True, ax=axs[1]);
```

The output of this snippet is cbarTrue.png.
![cbarTrue](https://user-images.githubusercontent.com/12193419/107731068-a1406180-6cba-11eb-8436-587f541e22b4.png)
On the other hand, setting `cbar=False` instead produces the result I would roughly expect, cbarFalse.png.
![cbarFalse](https://user-images.githubusercontent.com/12193419/107731080-a7ced900-6cba-11eb-8d62-34dfbe1c21f3.png)

Kindest regards,
Chuck

**Comment by andrzejnovak** [comment]
Hi @cburton12, thanks for reporting this. The reason for this is I've implemented the cbar in such a way that it doesn't change the original aspect ratio, which works for 1 plot, but sadly ends up being a bit tricky when more subplots are plotted.

**Comment by cburton12** [comment]
That makes sense. I'm a little busy with a paper at the moment, but can try to contribute a fix some other time. So, if someone finds this thread in the meantime and wants to make the PR, no need to wait around for me. :)

**Comment by andrzejnovak** [comment]
https://pypi.org/project/mplhep/0.2.16/ @cburton12  should fix this.
