### ISSUE TITLE
Other experiments for plots [Wish]

### ISSUE THREAD

**Issue by EnginEren** [scikit-hep/mplhep#260]
Dear authors, 

thank you very much for this excellent tool. It worked seamless when I produce my plots with `ROOT` style. 

I'm actually not part of any LHC experiments (I was in the past). I'm wondering whether it's possible to define other experiments like (FCC, CLIC, or even better ILD :) ) 

this is not an issue, just a very exciting wish :) 
cheers,
Engin

**Comment by andrzejnovak** [comment]
Hi @EnginEren, glad to hear you found it useful. I don't think there's anything constraining us to LHC experiments. However, for styles, we rely on member contributions.  If you'd like a more tailored style for your experiment you can take inspiration from the existing ones and submit a PR :)

**Comment by EnginEren** [comment]
Hi @andrzejnovak , sure.. good to hear that you're open to all other experiments. Will come with PR then :)
