### ISSUE TITLE
bh version can fail tests?

### ISSUE THREAD

**Issue by andrzejnovak** [scikit-hep/mplhep#269]
Looks like tests started failing 3 days ago for bh test https://github.com/scikit-hep/mplhep/actions/runs/583097024

@henryiii do we have some version mismatch?

![image](https://user-images.githubusercontent.com/13226500/108750046-d8c3cf00-7540-11eb-986d-0a21b0f3d52c.png)

**Comment by henryiii** [comment]
Yes, boost-histogram 0.13+ supports PlottableHistogram, which has error bars by default. We need to add `yerr=False` to those tests, just like we had to do for uproot. We should also have some error bar tests too. ;)

**Comment by henryiii** [comment]
I'll help with this soon. :)

**Comment by henryiii** [comment]
Correction, I think you beat me to it in #271 - can this be closed?

**Comment by andrzejnovak** [comment]
Yes, this is fixed. Seems, I forgot to close it.
