### ISSUE TITLE
How to use the same cbar for two 2dhistograms?

### ISSUE THREAD

**Issue by romanovzky** [scikit-hep/mplhep#270]
Hi there,

I am plotting multiple pairs of 2d histograms, and I would like to keep both the scale of the cbar and the cbar itself in a subplot, how can I accomplish this?

Cheers

**Comment by andrzejnovak** [comment]
I am not sure I understand, what does "scale of the cbar and the cbar itself" mean?

**Comment by romanovzky** [comment]
Sorry for being imprecise.

1) Share the cbar scale: I have two distinct 2d histograms. I want the "yellow" on one to mean the same number as the "yellow" on the other. I.e. keeping the cmap between the values and the colours.

2) Share the cbar: If I plot two both 2dhistograms in the same subplot, to have a single cbar (notice that this only makes sense if 1) is fulfilled, otherwise the histogram colours map to different numerical values of the histogram).

**Comment by andrzejnovak** [comment]
Ah I see. You should be able to specify `vmin, vmax` when creating the cbar. `hist2dplot` should take that iirs as well. So creating 
```
fig, ax1, ax2 = plt.subplots(1, 2)
```
and then 
```
hist2dplot(..., ax=ax1, cbar=False)
hist2dplot(..., ax=ax2)
```

**Comment by romanovzky** [comment]
Cheers, I'll have a go. Completely forgot about the `vmin`, `vmax`, for same reason I got my mind set on this idea of a `cmap` object that had to be shared and carried around. Nevermind...

**Comment by romanovzky** [comment]
I'm having issues with formatting, as the cbar is considered part of the second plot, the histogram itself is shrank to make space for the cbar, making it look smaller than the first one.

**Comment by romanovzky** [comment]
The solution that I found to work is to increase the figsize in the horizontal direction, but now I have a huge blank space between the two histograms, albeit they are the same shape and I have a colourbar.

**Comment by romanovzky** [comment]
Well, tweaking the figsize yields an acceptable look. I would still wish for better and/or more intuitive support for subplots with 2dhist.

**Comment by andrzejnovak** [comment]
I don't think we can generalize your use case here. There's way too much ambiguity if for N histograms and 1 cbar.

What you can do is create the figure/axes layout as you like (there's plenty of pure mpl examples) and then tell hist2dplot which axes to plot into. I.e separately create add,ax2,cbarax and then pass these in.

**Comment by romanovzky** [comment]
Hi again.

Yes, sure, that's what I do already. I think I got it to look better by removing `axs[0].set_box_aspect(1)` and `axs[1].set_box_aspect(1)`. 

Cheers, I'll close it.
