### ISSUE TITLE
docs: histplot(..., stack=True) to warn against multiple calls

### ISSUE THREAD

**Issue by alpha-oliveira** [scikit-hep/mplhep#272]
Version: mplhep==0.2.15
For instance, this simple code:
```
import numpy as np
import mplhep as hep
group1 = [1, 1, 1, 2, 2, 3, 4]
group2 = [2, 2, 2, 1, 1, 3, 1]
group3 = [3, 3, 3, 2, 2, 1, 2]

bins = [1,2,3,4,5,6,7]
g1,_ =np.histogram(group1,bins=bins)
g2,_=np.histogram(group2,bins=bins)
g3,_ =np.histogram(group3,bins=bins)


hep.histplot(g2,bins=bins, histtype='fill', stack=True ,  color='b')
hep.histplot(g1,bins=bins, histtype='fill', stack=True ,  color='g')

hep.histplot(g3,bins=bins, histtype='fill', stack=True,  color='y')
```
gives as outup a non stacked plot.
![toy](https://user-images.githubusercontent.com/728419/110525244-44df2f00-810c-11eb-8dd9-07935b22ece1.jpg)

**Comment by andrzejnovak** [comment]
Hi @alpha-oliveira, you are looking for a different syntax

```
hep.histplot([g1, g2, g3], bins=bins, histtype='fill', stack=True ,  color=['b', 'g', 'y'])
```

**Comment by asnaylor** [comment]
Hi @andrzejnovak, I did the same thing today trying to plot stacked histograms with multiple `histplot` calls instead of a single call with the multiple histograms in a list. I didn't see this in any of the documentation, please can you add it

**Comment by andrzejnovak** [comment]
We could possibly have a warning, but I'm not actually sure i understand the assumption here. How would histplot know a histogram is already drawn in the axes. All mpl artists are independent of one another. What would happen if you make two calls to hist with stack turned on but incompatible binning?

**Comment by asnaylor** [comment]
For me, moving over from ROOT I'm used to adding to an object one at at a time instead of passing all objects at once. With THStack you add your histograms one at a time and then draw the THStack object. I know that's not how this works but my thought is people might have gotten used to that ROOT style of one at a time so a warning or just something in the docs might be helpful.

**Comment by asnaylor** [comment]
Thanks @andrzejnovak 👍🏻
