### ISSUE TITLE
Remove strict SciPy dependency?

### ISSUE THREAD

**Issue by henryiii** [scikit-hep/mplhep#276]
mplhep has a strict dependency on SciPy, which is quite large. It might be be nice if this was optional. In Hist, we are trying to move to iMinuit instead of SciPy for fitting.

**Comment by andrzejnovak** [comment]
Hmm, `scipy` is currently used for error bars. I don't know if I have a clear opinion. Error bars are the kind of thing that someone installs `mplhep` and gets a missing dependency on the first function call, which is not great. Then again it's fair assumption most users already have it. 

Is there a way to do this conditionally? Aka `pip install mplhep` would include scipy, but something like `pip install mplhep[bare]` would not?

**Comment by henryiii** [comment]
No, you can't "remove" a dependency with an extra. Is it just for scipy.stats? scipy.stats is notoriously slow, possibly could be implemented without scipy?

**Comment by henryiii** [comment]
You could do mplhep-base which doesn't have it, and mplhep that does. But if it's for a pretty small thing, might be easier to just rework it.

**Comment by andrzejnovak** [comment]
Close via #282
