### ISSUE TITLE
Resting style

### ISSUE THREAD

**Issue by romanovzky** [scikit-hep/mplhep#278]
Hi there,

Sometimes I have to use two high-level plotting libraries, `mplhep` and `seaborn`, both of which define styles very aggressively which affect one-another. Sometimes I can avoid this by plotting `seaborn` things before `mplhep`, but sometimes that requires awkward change of code logic.

More precisely, if I use `mplhep.set_style(mplhep.style.ROOT)` before `seaborn.set_theme()`, `seaborn` plots are affected by aspect ratio, etc of `mplhep`. I tried to reset the styles with

```
import matplotlib as mpl
mpl.rcParams.update(mpl.rcParamsDefault)
```

but did not have any affect. How could I remove the styling from `mplhep` before using `seaborn`?

Cheers

**Comment by andrzejnovak** [comment]
Indeed using more than one still is likely to lead to unexpected results.
Your best bet it's loading both dictionaries and making the adjustments you
need

One  alternative is using the pythonic with ... construction, but it
doesn't play well with font choices.

**Comment by romanovzky** [comment]
`with ...` did the trick for me. I'm not being very picky about the fonts at this stage (I'm not preparing collaboration-ready plots), so this satisfies my use-case. Cheers
