### ISSUE TITLE
accent positioning for latex render

### ISSUE THREAD

**Issue by kratsg** [scikit-hep/mplhep#290]
see matplotlib/matplotlib#4561

running through `ATLAS` mplstyle renders as

<img width="349" alt="Screen Shot 2021-04-23 at 9 52 43 AM" src="https://user-images.githubusercontent.com/761483/115882329-a9372300-a41a-11eb-9010-5a433b643c03.png">

while running through ATLASTex style renders as

<img width="360" alt="Screen Shot 2021-04-23 at 9 58 11 AM" src="https://user-images.githubusercontent.com/761483/115882354-af2d0400-a41a-11eb-89e9-364e03ec9278.png">

maybe we should use a proper italics font for the `mathtext.it` option?

**Comment by andrzejnovak** [comment]
Hmm, I guess ` "mathtext.it": "TeX Gyre Heros:italic"` is not working as expected?

**Comment by kratsg** [comment]
Yeah, unsure. I think if I change the default

```
plt.rcParams.update({
    'mathtext.default': 'it'
})
```

then it looks better

![Screen Shot 2021-04-23 at 10 16 16 AM](https://user-images.githubusercontent.com/761483/115884488-f61bf900-a41c-11eb-81c9-66e1fb58bd24.png)

but still slightly off.

**Comment by andrzejnovak** [comment]
That makes sense (also looks like the Tex Gyre Heros italics). It cycles back to the fact that there aren't many open nice looking fonts with math characters - even less so that match the default Helvetica look

I expect `\mathit{}` would also work here.

**Comment by kratsg** [comment]
It does. I wonder if the default should be italicized or not given that we're using the custom font set. ./cc @matthewfeickert

**Comment by matthewfeickert** [comment]
> It does. I wonder if the default should be italicized or not given that we're using the custom font set. ./cc @matthewfeickert

Yeah, I would be in favor of this.
