### ISSUE TITLE
Add mplhep to matplotlib "Third party packages" page

### ISSUE THREAD

**Issue by matthewfeickert** [scikit-hep/mplhep#293]
@andrzejnovak Have you inquired before or made an Issue to add `mplhep` to `matplotlib`'s ["Third party packages" page](https://matplotlib.org/stable/thirdpartypackages/index.html)? With no disrespect to [`ridge_map`](https://matplotlib.org/stable/thirdpartypackages/index.html#ridge-map) (which I've used to make some home art before) I feel that if it has made the list then `mplhep` seems like it should be eligible as well. :)

**Comment by andrzejnovak** [comment]
Looks like we would qualify, but we have to submit the PR

**Comment by matthewfeickert** [comment]
This seems to be controlled through https://github.com/matplotlib/mpl-third-party so I'll make PR there.

**Comment by matthewfeickert** [comment]
@andrzejnovak with regards to getting `mplhep` added to https://matplotlib.org/stable/thirdpartypackages/index.html @tacaswell has mentioned

> That page is going away for 3.5, where you put it is fine

so I think we can safely say that this Issue was resolved by https://github.com/matplotlib/mpl-third-party/pull/75. :+1:
