### ISSUE TITLE
cmstext not working with scientific notation

### ISSUE THREAD

**Issue by jrueb** [scikit-hep/mplhep#30]
When one has very large numbers on the y axis, one can make use of scientific notation to make things more readable in matplotplib using `ax.ticklabel_format(axis="y", style="sci", scilimits=(0, 0))`. Matplotlib then will write e.g. 2.0 instead of 20000 as tick label and a 1e5 on the top left of the plot. Unfortunately this is exactly where mplhep.cms.cmstext places the "CMS" label and so they are on top of each other.

I understand one can adjust the location with the loc parameter, but that one only offers to move the label inside the plot. It would be preferable if one could place the "CMS" label next to the tick scale (outside the plot).

**Comment by andrzejnovak** [comment]
`next to the tick scale (outside the plot).` Could you add an example, I'm not 100% sure I get what oyu mean

**Comment by jrueb** [comment]
Right now it looks like this 
![Figure_1](https://user-images.githubusercontent.com/30041073/72269383-c67c1f80-3623-11ea-9aa0-9092fe834e5f.png)

and what I have in mind is something like this
![Figure_2](https://user-images.githubusercontent.com/30041073/72269407-d3990e80-3623-11ea-9474-ceccba430338.png)

Source
```
import matplotlib.pyplot as plt
import mplhep as hep
import numpy as np

data = np.random.rand(1000000)
ax = plt.gca()
hep.cms.cmslabel(ax)
plt.hist(data)
ax.ticklabel_format(axis="y", style="sci", scilimits=(0, 0))
plt.show()
```

**Comment by andrzejnovak** [comment]
I can take a look, It would be useful if we could get this behaviour automatically, but I am not sure how to fetch the Text object with the sci label

**Comment by andrzejnovak** [comment]
@jrueb  It might take me some time to get to it, but if you feel like fixing it, this get's you the offset of the exponent text `ax.get_yaxis().offsetText.get_tightbbox(ax.figure.canvas.renderer).width`

**Comment by andrzejnovak** [comment]
@jrueb 0.0.24 should fix it, let me know

**Comment by jrueb** [comment]
Thanks for the fix. Unfortunately it does not seem to work at all anymore if the y axis is set to logarithmic `ax.set_yscale("log")`.

I get `AttributeError: 'LogFormatterSciNotation' object has no attribute '_scientific'`. This is independent from the presence of a `ax.ticklabel_format` call.

**Comment by andrzejnovak** [comment]
Ugh, ok, that was unfortunate. Next version should properly check the formatter type first.

**Comment by andrzejnovak** [comment]
@jrueb did 0.0.25 fix this?

**Comment by jrueb** [comment]
Yes, it seems to work fine.
However, while I personally don't use it and did not consider it before, there is the possibility of `ax.yaxis.tick_right()` which moves the entire issue to the right side. mplhep does not check for this yet.

**Comment by andrzejnovak** [comment]
Ok, thanks for the heads up, but unless it comes up that's a #wontfix for me.
