### ISSUE TITLE
CONTRIBUTING.md specifies "complete" pip install extra

### ISSUE THREAD

**Issue by dantrim** [scikit-hep/mplhep#322]
The [CONTRIBUTING.md](https://github.com/scikit-hep/mplhep/blob/master/CONTRIBUTING.md) file gives the following command for installing the development environment:
```
python -m pip install --ignore-installed -U -e .[complete]
```
The current [setup.py](https://github.com/scikit-hep/mplhep/blob/master/setup.py) file does not define a "complete" extra, but instead only defines the `test`, `dev`, and `all` extra fields. 

# Observed behavior

Running the above command leads to:
```
$ python -m pip install --ignore-installed -U -e .[complete]
Obtaining file:///foo/bar/mplhep
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
WARNING: mplhep 0.3.9 does not provide the extra 'complete'
...
...
```

**Comment by matthewfeickert** [comment]
Thanks for catching this @dantrim &mdash; as well as for reading the `CONTRIBUTING.md`. :) I think this got [copied over from `pyhf`'s](https://github.com/scikit-hep/pyhf/blob/3ff84b6118619d63a5a07ca1a01e137ea4235984/CONTRIBUTING.md#installing-the-development-environment) by accident.

**Comment by andrzejnovak** [comment]
Quite so. Thanks for catching this.
