### ISSUE TITLE
Allow passthrough of label through ax kwarg

### ISSUE THREAD

**Issue by matthewfeickert** [scikit-hep/mplhep#327]
This was discussed a bit on Slack with @andrzejnovak and @alexander-held, but given a comment by Thomas I thought I'd give an example as an Issue and see if the suggestion is viable in @andrzejnovak's mind.

## Problem:

```python
import numpy as np
import matplotlib.pyplot as plt
import mplhep

import hist
from hist import Hist

np.random.seed(0)

hist_1 = Hist(hist.axis.Regular(10, 0.0, 1.0, name="x"))
hist_1.fill(np.random.random(1000))

fig, ax = plt.subplots()
mplhep.histplot(hist_1, ax=ax)
ax.set_xlabel("my label")  # want this to show up

hist_2 = Hist(hist.axis.Regular(10, 0.0, 1.0, name="x"))
hist_2.fill(np.random.random(1000))

# This overwrite the pervious label with the value of hist_2.axes[0].label, which is "x"
mplhep.histplot(hist_2, ax=ax)  # apparently the ax label info isn't used here?
fig.savefig("example.png", facecolor="white")
```

![example](https://user-images.githubusercontent.com/5142394/128389659-ec723d55-5c5c-4f44-8146-1d60b80afcf8.png)

Thomas mentioned

> behavior of checking if `ax.get_label() != '`:  before being helpful and setting the label seems reasonable to me. This is more or less what Matplotlib does with auto limits (if the user call `set_xlim` or `set_ylim` we track that and stop trying to help, but if not, then we re-compute the autolimits every time you add an artist

So if this is agreeable what would be needed (and what I have on a branch) is changing

https://github.com/scikit-hep/mplhep/blob/055a9fb4769beb1c1a571d71e346c84ce23caa3e/src/mplhep/plot.py#L167

to
```diff
-    x_axes_label = get_histogram_axes_title(hists[0].axes[0])
+    x_axes_label = (
+        get_histogram_axes_title(hists[0].axes[0])
+        if ax.get_xlabel() == ""
+        else ax.get_xlabel()
+    )
```

With this in the example code gives the following instead

![patch_example](https://user-images.githubusercontent.com/5142394/128390380-4194b74a-6367-4bcc-8247-6edd83231439.png)

@andrzejnovak  thoughts?

**Comment by matthewfeickert** [comment]
(I'll preface this with saying that all of this is my view as a user, and it is very possible that I'm missing a design intention here.)

Another reason I would suggest this, is that the current behavior isn't safeguarding the user, given the following:

```python
import numpy as np
import matplotlib.pyplot as plt
import mplhep

import hist
from hist import Hist

np.random.seed(0)

hist_1 = Hist(hist.axis.Regular(10, 0.0, 1.0, name="x", label="A"))
hist_1.fill(np.random.random(1000))

hist_2 = Hist(hist.axis.Regular(10, 0.0, 1.0, name="notx", label="B"))
hist_2.fill(np.random.random(1000))

fig, ax = plt.subplots()
mplhep.histplot(hist_1, label=f"{hist_1.axes[0].label}: {hist_1.axes[0].name}", ax=ax)
mplhep.histplot(hist_2, label=f"{hist_2.axes[0].label}: {hist_2.axes[0].name}", ax=ax)
ax.legend(loc="best")

fig.savefig("example.png", facecolor="white")
```

![example](https://user-images.githubusercontent.com/5142394/128418789-deca63d7-1404-43cf-8d48-84da1108c3a9.png)



While trying to add these two histogram together will properly have `hist` yell at you

```pytb
>>> hist_1 + hist_2
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-7-902e690dced8> in <module>
----> 1 hist_1 + hist_2

/srv/conda/envs/notebook/lib/python3.7/site-packages/boost_histogram/_internal/hist.py in __add__(self, other)
    315     def __add__(self: H, other: Union["Histogram", np.ndarray, float]) -> H:
    316         result = self.copy(deep=False)
--> 317         return result.__iadd__(other)
    318 
    319     def __iadd__(self: H, other: Union["Histogram", np.ndarray, float]) -> H:

/srv/conda/envs/notebook/lib/python3.7/site-packages/boost_histogram/_internal/hist.py in __iadd__(self, other)
    320         if isinstance(other, (int, float)) and other == 0:
    321             return self
--> 322         self._compute_inplace_op("__iadd__", other)
    323 
    324         # Addition may change the axes if they can grow

/srv/conda/envs/notebook/lib/python3.7/site-packages/boost_histogram/_internal/hist.py in _compute_inplace_op(self, name, other)
    360         # Also takes CppHistogram, but that confuses mypy because it's hard to pick out
    361         if isinstance(other, Histogram):
--> 362             getattr(self._hist, name)(other._hist)
    363         elif isinstance(other, tuple(_histograms)):
    364             getattr(self._hist, name)(other)

ValueError: axes not mergable
```

the above example does't keep them from being plotted together, but the second one has overwritten the axis label of the first.

**Comment by andrzejnovak** [comment]
@matthewfeickert On reflection, I think you are right simply because once a property was set, magic shouldn't mess with it. Doesn't matter if it was originally set by the user manually or by other magic. Feel free to PR or I can add it to the backlog.

What do you think of emitting a warning in case the new hist axis doesn't match existing? Would that lead to too much spam?

**Comment by matthewfeickert** [comment]
> Feel free to PR or I can add it to the backlog.

:+1: WIP over at PR #328

> What do you think of emitting a warning in case the new hist axis doesn't match existing? Would that lead to too much spam?

I'm fine with that, and it is probably helpful to give a heads up. Though what are other people's thoughts? @henryiii @kratsg

**Comment by matthewfeickert** [comment]
> What do you think of emitting a warning in case the new hist axis doesn't match existing? Would that lead to too much spam?

@andrzejnovak Actually, how does this work technically? I don't see how you'd be able to keep track of this between calls unless you kept an internal reference to the values of the `hist.axes` for a particular `ax` object. Am I missing something?
