### ISSUE TITLE
Add HEAD of dependencies GHA workflow 

### ISSUE THREAD

**Issue by matthewfeickert** [scikit-hep/mplhep#373]
Hi @andrzejnovak. Now that `matplotlib` has public nightly wheels (c.f. https://github.com/matplotlib/matplotlib/pull/22733) would you be interested in a "HEAD of dependencies workflow" that runs nightly to test against the `HEAD` on GitHub or nightlies of the core dependencies

https://github.com/scikit-hep/mplhep/blob/7a20bbd56b5ca4e9029a26400ae0873afc77badd/setup.cfg#L27-L32

? If so, I can basically port over [the one we have for `pyhf`](https://github.com/scikit-hep/pyhf/blob/0a8f3282e9bc6d66b3e596fd35c74a6e03ff567a/.github/workflows/dependencies-head.yml) and PR it for you here.

**Comment by andrzejnovak** [comment]
Oh nice, yeah that looks very useful and would be a welcome addition.
