### ISSUE TITLE
CI failing

### ISSUE THREAD

**Issue by jonas-eschle** [scikit-hep/mplhep#407]
Currently, the CI is failing here: https://github.com/scikit-hep/mplhep/actions/runs/3576833992/jobs/6015113800

Any ideas @andrzejnovak ?

**Comment by andrzejnovak** [comment]
I know about it, didn't have time to fix it yet. It's not tied to any change in the code, so most likely something changed about `pytest-mpl`. Can ignore this for the docs change.
