### ISSUE TITLE
Incorrect flow bin labeling

### ISSUE THREAD

**Issue by atownse2** [scikit-hep/mplhep#501]
Here is a reproducer, using the main branch:
```python
import mplhep as hep
import hist

h = hist.Hist(
    hist.axis.Regular(4, 0.1, 0.9, underflow=True, overflow=True)
    ).fill(1*np.random.rand(1000))
hep.histplot(h, flow='show', label='h')

plt.show()
```
Which produces:
![4d271f4f-c26c-4af4-90a4-08d2db534d70](https://github.com/scikit-hep/mplhep/assets/47793576/3fd846a8-14e7-439d-a398-0fe1ba0d493a)

It looks like the [xtick labels](https://github.com/scikit-hep/mplhep/blob/c5664ba8858ace55ae6bfb96e9f942d1ae659e93/src/mplhep/plot.py#L564) are using the wrong values in `flow_bins` - modifying the indices used produces this plot:
![55aa4c23-f8cf-4a87-948c-89ca288ad1ba](https://github.com/scikit-hep/mplhep/assets/47793576/1797520e-a426-47bb-a717-05fb2dbbb300)

This looks nice if the bin centers line up with the x-ticks, however when this isn't the case you get:
![8e40351b-21e1-47c8-b912-1fd1977ef9d1](https://github.com/scikit-hep/mplhep/assets/47793576/8f0fc0d5-3b78-4928-9eff-6f9f3d457fe8)

This seems confusing - one possible solution is to replace any existing ticks in the flow bins with the flow bin center and label that. Doing this results in:
![b98f4458-ac8a-40de-b9ef-9d73956c8aea](https://github.com/scikit-hep/mplhep/assets/47793576/4c2b6383-27c4-4f61-9e4f-147b992e1923)

I can make a PR with these changes if wanted.

**Comment by atownse2** [comment]
Also, when the axes passed to `histplot` have a shared x-axis, the `xticklabels` are sometimes empty, breaking the current code. After messing around for a bit I can get plots like this:
```python
h = hist.Hist(
    hist.axis.Variable([0.1, 0.4, 0.5, 0.9], underflow=True, overflow=True)
    ).fill(1*np.random.rand(1000))

fig, ax = plt.subplots(2, 1, sharex=True, gridspec_kw={'hspace': 0})

hep.histplot(h, flow='show', label='h', ax=ax[0])
hep.cms.label(ax=ax[0], data=False, year=2016)

# Draw random data on bottom plot
r = h.copy().reset().fill(1*np.random.uniform(0.1, 1, 1000))
hep.histplot(r, flow='show', label='r', ax=ax[1])

plt.show()
```
I can get:
![00f56822-369a-45bb-8103-20789f70127d](https://github.com/scikit-hep/mplhep/assets/47793576/ab993121-6a46-4069-81ec-cd2e44a70c08)

**Comment by andrzejnovak** [comment]
HI @atownse2 thanks for the report. If you have the bandwidth to PR a fix, that be awesome!
