### ISSUE TITLE
Improving interface to plotting tool

### ISSUE THREAD

**Issue by acampove** [scikit-hep/mplhep#533]
Hi,

Thanks for this project. However, from a user POV I think a friendlier way to plot is like:

https://github.com/acampove/dmu?tab=readme-ov-file#2d-plots

Which is implemented with histograms from `hist` and using `mplhep` for plotting. However I feel this interface is less verbose for the user. Maybe you would consider this approach and you could extend this tool in that direction. Feel free to take whatever code you want from that repository.

Cheers.

**Comment by andrzejnovak** [comment]
Hi @acampove. Thanks for reaching out. For now the `mplhep` scope is envisoned to be somewhat limited as we're intending to keep it as an intuitive extension on `matplotlib`. However, it's great to hear you found it useful when designing a more custom ADL-like plotting interface
