### ISSUE TITLE
Create multiple versions of plots with different annotations

### ISSUE THREAD

**Issue by cranmer** [scikit-hep/mplhep#61]
**Feature request:**

Often we need to make multiple versions of the same plot for different stages of approval. 
Could consider a utility that creates the same plot with several different annotations ("in progress", "internal", official) with some standard naming convention or folder structure.

**Comment by andrzejnovak** [comment]
What kind of API would you have in mind?

There is currently a convenience function just for this
```
import mplhep as hep
import matplotlib.pyplot as plt
plt.style.use(hep.style.ATLAS)

fig, axs = plt.subplots(4)
fig.subplots_adjust(hspace=1)
hep.atlas.atlaslabel(ax=axs[0])
hep.atlas.atlaslabel(ax=axs[1], data=True)
hep.atlas.atlaslabel(ax=axs[2], paper=True)
hep.atlas.atlastext("Work-in-progress", ax=axs[3])
```
![image](https://user-images.githubusercontent.com/13226500/74665792-a4386d00-51a0-11ea-95b2-f8a40fcfbeae.png)
