### ISSUE TITLE
hist2dplot should not require transposing 

### ISSUE THREAD

**Issue by HDembinski** [scikit-hep/mplhep#76]
In this example on the frontpage
```
import numpy as np
import matplotlib.pyplot as plt
import mplhep as hep

fig, ax = plt.subplots()

xedges = [0, 1, 3, 5]
yedges = [0, 2, 3, 4, 6,7]
x = np.random.normal(2, 1, 100)
y = np.random.normal(4, 1, 100)
H, xedges, yedges = np.histogram2d(x, y, bins=(xedges, yedges))
H = H.T

hep.hist2dplot(H, xedges, yedges)
```
the line `H = H.T` shouldn't be necessary. You need to transpose for `pcolor`, but because `pcolor` was never made for histograms, it was made for images. `hist2dplot` should not copy this unnecessary step, since it is specifically for histograms.

**Comment by andrzejnovak** [comment]
I forget if I updated this, but yeah `hist2dplot` should hide it inside, so stuff like`hist2dplot(*np.histogram2d(...))` is possible
