### ISSUE TITLE
Better function names

### ISSUE THREAD

**Issue by HDembinski** [scikit-hep/mplhep#77]
The chosen function names are not ideal.

*histplot* -> *hist*
- `histplot` is not Pythonic snake_case, it should have been `hist_plot` for better readability but actually...
- since it is supposed to mimic `plt.hist`, it should have the same name

*hist2dplot* -> *hist2* or *hist2d*
- the`plot` at the end is superfluous, and again it is not proper snake_case

**Comment by andrzejnovak** [comment]
I'm open to renamings, but I would want to avoid overlap with pyplot namespace in case we ever switch to monkeyclassing

**Comment by HDembinski** [comment]
You should not try to avoid name clashes. We have namespaces to resolve the ambiguity. That's the reason everyone writes `plt.hist` instead of just `hist`, so that this package can also have a `hist`.

**Comment by HDembinski** [comment]
Look at cupy, jax, etc, these re-implement the numpy interface with the exact same names and calling conventions under a different namespace, precisely so that you can do
```
# import numpy as np
from jax import numpy as np

# do numpy stuff
```

**Comment by andrzejnovak** [comment]
But they keep the api close to same right? Whereas here we change what
"hist" is expecting.

What do we then do if we decide to monkeyclass histplot onto pyplot. Or if
we manage to convince mpl to actually have a histogram plotting fcn.

**Comment by HDembinski** [comment]
Ok, you are right, it is not exactly the same situation. If I understand correctly, you are already preparing for a possible merging of mplhep into pyplot. I think this is not going to happen very soon, and even when it is, the names will be debated again anyway. You cannot anticipate how that merging will go. The matplotlib guys could decide to place this in mpl_toolkit, then you would have an extra namespace anyway.

For now, we should use names that are easy to type. I like the idea of imitating the pyplot.hist and hist2d interface, so that it is easy to switch over and you do not have to relearn another interface, that is great. However, the following should work
```py
mplhep.hist(*np.histogram(data))
```

**Comment by andrzejnovak** [comment]
@HDembinski Would you find it a reasonable solution to alias the two for now? `hist = histplot`, `hist2d = hist2dplot` ?

**Comment by HDembinski** [comment]
Yes, and to deprecate `histplot` and `hist2dplot`.

**Comment by HDembinski** [comment]
This is the deprecation decorator I use in iminuit, feel free to copy this or allow me to make a PR with the change.
https://github.com/scikit-hep/iminuit/blob/develop/iminuit/_deprecated.py
