### ISSUE TITLE
General API parity between cms.style and atlas.style desirable

### ISSUE THREAD

**Issue by matthewfeickert** [scikit-hep/mplhep#8]
It would be nice if there were greater API parity between [`mplhep.cms.style`](https://github.com/andrzejnovak/mplhep/blob/a923cd57fa16078a241afec8656c8bcd51be305e/mplhep/styles_cms.py) and [`mplhep.atlas.style`](https://github.com/andrzejnovak/mplhep/blob/a923cd57fa16078a241afec8656c8bcd51be305e/mplhep/styles_atlas.py) so that the examples were more translatable across experiment. There is no need for them to be _identical_ but keeping them close is desirable. As @kratsg is the one we have to thank for `mplhep.atlas.style.ATLAS` existing at all in the first place more follow up with him might be necessary.

**Comment by andrzejnovak** [comment]
I agree. `cms.style` contains styling helpers I use specifically for CMS. I'd be happy to include equivalent functions for ATLAS, but I don't know what is typically needed.

**Comment by kratsg** [comment]
I don't understand what API parity means here. There's no special function for atlas styles specifically, other than importing and setting the mpl styles. I didn't use anything more to make our plots for the pyhf pub notes.

**Comment by andrzejnovak** [comment]
Right now the only CMS specific part is the main plot label i.e. **CMS** _Preliminary_ , which is a bit finicky to get right, which is why I outsourced it here. We could presumably do something similar for ATLAS.

**Comment by matthewfeickert** [comment]
> I don't understand what API parity means here.

Perhaps "consistency" is a better choice of words? I just mean that if you look at [`mplhep.cms.style`](https://github.com/andrzejnovak/mplhep/blob/a923cd57fa16078a241afec8656c8bcd51be305e/mplhep/styles_cms.py) and [`mplhep.atlas.style`](https://github.com/andrzejnovak/mplhep/blob/a923cd57fa16078a241afec8656c8bcd51be305e/mplhep/styles_atlas.py) there are currently different in that the `README` shows that one must do

```
plt.style.use(hep.cms.style.ROOT)
plt.style.use(hep.atlas.style.ATLAS)
```

to use different styles. It would be nicer in my mind to have them be unified such that for the different experiments one would just do

```
plt.style.use(hep.<experiment>.style.ROOT)
```

**Comment by andrzejnovak** [comment]
While I agree in general, as of now, we have only two styles. I am also not sure if there are meaningful differences between general ROOT and specific CMS (maybe figure aspect).

I also originally thought to have all styles unique, such that they can be called as `hep.style.ATLAS` or hard copied to mpl cache, but I'm happy to revise it.

**Comment by matthewfeickert** [comment]
> I also originally thought to have all styles unique, such that they can be called as `hep.style.ATLAS`

Fair. Whatever API you prefer is fine by me, just let me know, and we can go from there.

**Comment by andrzejnovak** [comment]
@matthewfeickert @kratsg One obvious thing to generalize is the experiment label (`hep.cms.cmslabel`) could you post some examples/spec of the labelling typically used in ATLAS?

**Comment by kratsg** [comment]
```yaml
atlas: &atlas
  x: 0.225
  y: 0.88
  font: 73
  size: 25
  label: ATLAS

internal: &internal
  x: 0.35
  font: 43
  label: Internal
  <<: *atlas

atlasinternal: &atlasinternal
  - *atlas
  - *internal
```

used in this code: https://github.com/kratsg/TakeOverTheWorld/blob/989c97382689d77649bdf29e00f10d509a6c7b90/totw.py#L413-L421

**Comment by andrzejnovak** [comment]
So really pretty much the same as for CMS right?

**Comment by kratsg** [comment]
> So really pretty much the same as for CMS right?

It _should_ be. we should build the generic `addExperimentLabel` function and then an `addATLASLabel / addCMSLabel`.

**Comment by andrzejnovak** [comment]
#39 should add atlas options
```
hep.atlas.atlastext()
hep.atlas.atlaslabel().
```
I'm open to better names

**Comment by andrzejnovak** [comment]
@matthewfeickert @kratsg anything else or can I close this?
