### ISSUE TITLE
Add Jupyter notebooks as demos/tutorials

### ISSUE THREAD

**Issue by HDembinski** [scikit-hep/mplhep#96]
The documention in the README is pretty good, but it would be even better to include Jupyter notebooks in the repository under a directory "tutorials" or "examples" which show how to make typical plots.

**Comment by eduardo-rodrigues** [comment]
Agreed. If you look at Particle, DecayLanguage and boost-histogram you will see that they all contain a `notebooks` directory. @andrzejnovak, how about that?

**Comment by andrzejnovak** [comment]
I agree this should be updated. Ideally into a binder along with Nicks mpl-hep gallery. It's on my long term to-do, but a PR is welcome

**Comment by HDembinski** [comment]
Short-term, you can add this directory "notebooks" and move "Examples.ipynb" there.
